### ISSUE TITLE
Apple mail export .mbox problem?

### ISSUE THREAD

**Issue by okcomputer-1** [google/import-mailbox-to-gmail#15]
I am trying to migrate mbox files that I exported from the Apple mail software.
However, the system says can't process mbox files for user xxxx@yyyy.com
And then says: 

IOErrr: [Errno 21] Is a directory: "Users/.../..../ xxxxx.mbox'

I have the fear that the Apple does not extract compatible mbox files for the migration. Any help is welcome.

**Comment by eesheesh** [comment]
Can you share the full log file (after redacting any private information)?

**Comment by okcomputer-1** [comment]
2016-07-01T16:33:46 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:285) *** Starting import-mailbox-to-gmail 1.3 on Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 26 2016, 12:10:39)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] ***
2016-07-01T16:33:46 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:286) Arguments:
2016-07-01T16:33:46 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:288)     auth_host_name: 'localhost'
2016-07-01T16:33:46 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:288)     auth_host_port: [8080, 8090]
2016-07-01T16:33:46 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:288)     dir: '/Users/username/Downloads/Gmail_migration/mbox/'
2016-07-01T16:33:46 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:288)     fix_msgid: True
2016-07-01T16:33:46 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:288)     httplib2debuglevel: 0
2016-07-01T16:33:46 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:288)     json: 'Credentials.json'
2016-07-01T16:33:46 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:288)     log: 'import-mailbox-to-gmail-2933.log'
2016-07-01T16:33:46 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:288)     logging_level: 'INFO'
2016-07-01T16:33:46 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:288)     noauth_local_webserver: False
2016-07-01T16:33:46 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:288)     num_retries: 10
2016-07-01T16:33:46 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:288)     replace_quoted_printable: True
2016-07-01T16:33:46 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:301) Processing user email@account.com
2016-07-01T16:33:46 (+0100) 2933 INFO method (discovery.py:822) URL being requested: GET https://www.googleapis.com/gmail/v1/users/email%40account.com/labels?fields=labels%28id%2Cname%29&alt=json
2016-07-01T16:33:46 (+0100) 2933 INFO new_request (client.py:614) Attempting refresh to obtain initial access_token
2016-07-01T16:33:46 (+0100) 2933 INFO _do_refresh_request (client.py:903) Refreshing access_token
2016-07-01T16:33:50 (+0100) 2933 INFO process_mbox_files (import-mailbox-to-gmail.py:174) Skipping '/Users/username/Downloads/Gmail_migration/mbox/email@account.com/.DS_Store' because it doesn't have a .mbox extension
2016-07-01T16:33:50 (+0100) 2933 INFO process_mbox_files (import-mailbox-to-gmail.py:176) Starting processing of '/Users/username/Downloads/Gmail_migration/mbox/email@account.com/Potentials.mbox'
2016-07-01T16:33:50 (+0100) 2933 ERROR main (import-mailbox-to-gmail.py:324) Can't process mbox files for user email@account.com
2016-07-01T16:33:50 (+0100) 2933 ERROR main (import-mailbox-to-gmail.py:347) Can't process user email@account.com
Traceback (most recent call last):
  File "import-mailbox-to-gmail.py", line 322, in main
    result = process_mbox_files(username, service, labels)
  File "import-mailbox-to-gmail.py", line 179, in process_mbox_files
    mbox = mailbox.mbox(full_filename)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mailbox.py", line 832, in __init__
    _mboxMMDF.__init__(self, path, factory, create)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mailbox.py", line 571, in __init__
    f = open(self._path, 'rb+')
IOError: [Errno 21] Is a directory: '/Users/username/Downloads/Gmail_migration/mbox/email@account.com/xxx.mbox'
2016-07-01T16:33:50 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:348) *** Done importing all users from directory '/Users/username/Downloads/Gmail_migration/mbox/'
2016-07-01T16:33:50 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:349) *** Import summary:
2016-07-01T16:33:50 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:351)     0 users imported with no failures
2016-07-01T16:33:50 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:353)     0 users imported with some failures
2016-07-01T16:33:50 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:355)     1 users failed
2016-07-01T16:33:50 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:357)     0 labels (mbox files) imported with no failures
2016-07-01T16:33:50 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:359)     0 labels (mbox files) imported with some failures
2016-07-01T16:33:50 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:361)     0 labels (mbox files) failed
2016-07-01T16:33:50 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:363)     0 messages imported successfully
2016-07-01T16:33:50 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:365)     0 messages failed

2016-07-01T16:33:50 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:368) *** Check log file import-mailbox-to-gmail-2933.log for detailed errors.
2016-07-01T16:33:50 (+0100) 2933 INFO main (import-mailbox-to-gmail.py:369) Finished.

**Comment by brianebeyer** [comment]
The .mbox file you're looking for to import is inside the "xxxx.mbox" directory created by your Apple Mail export.

**Comment by yaaax** [comment]
Thanks @brianebeyer, that made my day !

**Comment by eesheesh** [comment]
Thanks @brianebeyer!

**Comment by priyaruby86** [comment]
If you want to import apple mails .mbox file to gmail account, then read this blog, it may help you: https://tech-vita.blogspot.com/2018/12/how-to-import-mbox-to-gmail.html

**Comment by eesheesh** [comment]
Note that importing large amounts of mail using IMAP (as that post suggests) isn't recommended, as Gmail IMAP upload limit is quite small - [500mb per day](https://support.google.com/a/answer/1071518).

Also, that post suggests using a username+password, which isn't as secure as using OAuth (which Thunderbird supports).
