### ISSUE TITLE
os.walk error

### ISSUE THREAD

**Issue by jevilsizor** [google/import-mailbox-to-gmail#42]
(Python2.7) root@LT2226:/mnt/c/python# python import-mailbox-to-gmail.py --json /MBOX/Credentials.json --dir /MBOX --logging_level INFO
15:31:08 INFO main@import-mailbox-to-gmail.py *** Starting import-mailbox-to-gmail 1.5 on Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] ***
15:31:08 INFO main@import-mailbox-to-gmail.py Arguments:
15:31:08 INFO main@import-mailbox-to-gmail.py   auth_host_name: 'localhost'
15:31:08 INFO main@import-mailbox-to-gmail.py   auth_host_port: [8080, 8090]
15:31:08 INFO main@import-mailbox-to-gmail.py   dir: '/MBOX'
15:31:08 INFO main@import-mailbox-to-gmail.py   fix_msgid: True
15:31:08 INFO main@import-mailbox-to-gmail.py   from_message: 0
15:31:08 INFO main@import-mailbox-to-gmail.py   httplib2debuglevel: 0
15:31:08 INFO main@import-mailbox-to-gmail.py   json: '/MBOX/Credentials.json'
15:31:08 INFO main@import-mailbox-to-gmail.py   log: 'import-mailbox-to-gmail-535.log'
15:31:08 INFO main@import-mailbox-to-gmail.py   logging_level: 'INFO'
15:31:08 INFO main@import-mailbox-to-gmail.py   noauth_local_webserver: False
15:31:08 INFO main@import-mailbox-to-gmail.py   num_retries: 10
15:31:08 INFO main@import-mailbox-to-gmail.py   replace_quoted_printable: True
Traceback (most recent call last):
  File "import-mailbox-to-gmail.py", line 415, in <module>
    main()
  File "import-mailbox-to-gmail.py", line 341, in main
    for username in next(os.walk(args.dir))[1]:
StopIteration

any ideas?

**Comment by eesheesh** [comment]
Based on https://stackoverflow.com/a/37289741/3275273, it looks like the directory you specified (`/MBOX`) doesn't exist. Please let me know if this is the case.

I'll leave this open anyway because it needs a better error message.

Thanks for reporting!

**Comment by jevilsizor** [comment]
It does exist.

I'm running my script from c:/python and the full path for mbox is
c:/python/mbox

I've tried putting the full path as well with the same results.

Those are the only errors I've gotten and mimics exactly what's in the log
file

**Comment by eesheesh** [comment]
In that case, you should probably use `-dir mbox`, without the slash. The slash means it will search for `c:\mbox`.

Also, in Windows it's generally better to use backslashes for paths, as not everything works well with forward slashes.

Please let me know if it works.

Thanks!

**Comment by jevilsizor** [comment]
That resolved my os.walk error.. but not it's telling me it can't find my Credentials.json file....

0:53:26 INFO main@import-mailbox-to-gmail.py   httplib2debuglevel: 0
10:53:26 INFO main@import-mailbox-to-gmail.py   json: 'C:/Credentials.json'
10:53:26 INFO main@import-mailbox-to-gmail.py   log: 'import-mailbox-to-gmail-658.log'
10:53:26 INFO main@import-mailbox-to-gmail.py   logging_level: 'INFO'
10:53:26 INFO main@import-mailbox-to-gmail.py   noauth_local_webserver: False
10:53:26 INFO main@import-mailbox-to-gmail.py   num_retries: 10
10:53:26 INFO main@import-mailbox-to-gmail.py   replace_quoted_printable: True
10:53:26 INFO main@import-mailbox-to-gmail.py Processing user mboxtest@powernetco.com
10:53:26 ERROR main@import-mailbox-to-gmail.py Can't get access token for user mboxtest@powernetco.com
10:53:26 ERROR main@import-mailbox-to-gmail.py Can't process user mboxtest@powernetco.com
Traceback (most recent call last):
  File "import-mailbox-to-gmail.py", line 345, in main
    credentials = get_credentials(username)
  File "import-mailbox-to-gmail.py", line 130, in get_credentials
    scopes=SCOPES).create_delegated(username)
  File "/usr/local/lib/python3.5/dist-packages/oauth2client/service_account.py", line 219, in from_json_keyfile_name
    with open(filename, 'r') as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Credentials.json'
