### ISSUE TITLE
NameError: name 'unicode' is not defined

### ISSUE THREAD

**Issue by greatestradioshow** [google/import-mailbox-to-gmail#59]
When running the script, I receive the following error:

```
PS D:\import> python import-mailbox-to-gmail.py --json Credentials.json --dir D:\import\mbox
20:11:09 INFO main@import-mailbox-to-gmail.py *** Starting import-mailbox-to-gmail 1.5 on Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] ***
20:11:09 INFO main@import-mailbox-to-gmail.py Arguments:
20:11:09 INFO main@import-mailbox-to-gmail.py   auth_host_name: 'localhost'
20:11:09 INFO main@import-mailbox-to-gmail.py   auth_host_port: [8080, 8090]
20:11:09 INFO main@import-mailbox-to-gmail.py   dir: 'D:\\import\\mbox'
20:11:09 INFO main@import-mailbox-to-gmail.py   fix_msgid: True
20:11:09 INFO main@import-mailbox-to-gmail.py   from_message: 0
20:11:09 INFO main@import-mailbox-to-gmail.py   httplib2debuglevel: 0
20:11:09 INFO main@import-mailbox-to-gmail.py   json: 'Credentials.json'
20:11:09 INFO main@import-mailbox-to-gmail.py   log: 'import-mailbox-to-gmail-1712.log'
20:11:09 INFO main@import-mailbox-to-gmail.py   logging_level: 'INFO'
20:11:09 INFO main@import-mailbox-to-gmail.py   noauth_local_webserver: False
20:11:09 INFO main@import-mailbox-to-gmail.py   num_retries: 10
20:11:09 INFO main@import-mailbox-to-gmail.py   replace_quoted_printable: True
Traceback (most recent call last):
  File "import-mailbox-to-gmail.py", line 416, in <module>
    main()
  File "import-mailbox-to-gmail.py", line 342, in main
    for username in next(os.walk(unicode(args.dir)))[1]:
NameError: name 'unicode' is not defined
```

Is it possible I get the error because I try running the script with a Gmail account, not Workspace?

**Comment by eesheesh** [comment]
I suspect that it's because you're using Python 3, and this script was written for Python 2.7. However, it doesn't matter, because it won't work for a @gmail.com account, only Workspace accounts. :)

I'd suggest https://github.com/google/mail-importer for migrating into @gmail.com accounts.

**Comment by eesheesh** [comment]
Updated to Python 3 with #65. If you still encounter any problems please create a new issue.
